// Starter recipes for the web store (English + Tamil). Added once from
// Web Store > Recipes > "Add starter recipes"; the shop can edit them.
// 'keys' auto-link each recipe to a matching product (first match wins).
const List<Map<String, Object>> starterRecipes = [
  {
    'id': 'ragi_kanji',
    'name': 'Ragi kanji',
    'nameLocal': 'ராகி கஞ்சி',
    'minutes': 15,
    'serves': 2,
    'keys': ['ragi flour', 'ragi'],
    'ingredients': ['3 tbsp ragi flour', '2 cups water', '1 cup buttermilk (or milk)', 'Salt to taste (or jaggery for a sweet version)', '1 small onion, finely chopped (optional)'],
    'ingredientsLocal': ['3 மேசைக்கரண்டி ராகி மாவு', '2 கப் தண்ணீர்', '1 கப் மோர் (அல்லது பால்)', 'தேவைக்கு உப்பு (இனிப்புக்கு வெல்லம்)', '1 சிறிய வெங்காயம், பொடியாக நறுக்கியது (விருப்பம்)'],
    'steps': ['Mix the ragi flour in half a cup of water without lumps.', 'Boil the remaining water and pour in the ragi mixture, stirring continuously.', 'Cook on low flame for 5–7 minutes until it thickens and turns glossy.', 'Cool slightly, add buttermilk and salt (or milk and jaggery), mix and serve.'],
    'stepsLocal': ['ராகி மாவை அரை கப் தண்ணீரில் கட்டியில்லாமல் கரைக்கவும்.', 'மீதி தண்ணீரை கொதிக்க வைத்து, ராகி கலவையை ஊற்றி தொடர்ந்து கிளறவும்.', 'குறைந்த தீயில் 5–7 நிமிடம் கெட்டியாகும் வரை வேக வைக்கவும்.', 'சற்று ஆறியதும் மோர், உப்பு (அல்லது பால், வெல்லம்) சேர்த்து கலந்து பரிமாறவும்.'],
    'benefits': ['Ragi is a good source of calcium and iron', 'A light, filling breakfast that keeps you full longer'],
    'benefitsLocal': ['ராகியில் கால்சியம், இரும்புச்சத்து நிறைந்துள்ளது', 'வயிறு நிறைந்த, எளிதில் செரிக்கும் காலை உணவு'],
    'tip': 'The sweet version with milk and cardamom is a favourite with children.',
    'tipLocal': 'பால், ஏலக்காய் சேர்த்த இனிப்பு கஞ்சி குழந்தைகளுக்குப் பிடிக்கும்.',
  },
  {
    'id': 'ragi_dosa',
    'name': 'Ragi dosa',
    'nameLocal': 'ராகி தோசை',
    'minutes': 20,
    'serves': 3,
    'keys': ['ragi flour', 'ragi'],
    'ingredients': ['1 cup ragi flour', '1/4 cup rice flour', '1 small onion, chopped', '1 green chilli, chopped', 'Curry leaves and coriander', 'Salt, and water as needed'],
    'ingredientsLocal': ['1 கப் ராகி மாவு', '1/4 கப் அரிசி மாவு', '1 சிறிய வெங்காயம், நறுக்கியது', '1 பச்சை மிளகாய், நறுக்கியது', 'கறிவேப்பிலை, கொத்தமல்லி', 'உப்பு, தேவைக்கு தண்ணீர்'],
    'steps': ['Mix both flours with salt and water to a thin, pourable batter.', 'Add onion, chilli, curry leaves and coriander; rest for 10 minutes.', 'Heat a tawa and pour the batter from the edges inward, like rava dosa.', 'Drizzle oil, cook till crisp and serve hot with chutney.'],
    'stepsLocal': ['இரண்டு மாவையும் உப்பு, தண்ணீருடன் நீர்க்க கரைக்கவும்.', 'வெங்காயம், மிளகாய், கறிவேப்பிலை, கொத்தமல்லி சேர்த்து 10 நிமிடம் வைக்கவும்.', 'தோசைக்கல்லை சூடாக்கி, ரவா தோசை போல ஓரத்திலிருந்து உள்ளே ஊற்றவும்.', 'எண்ணெய் விட்டு மொறுமொறுப்பாக சுட்டு சட்னியுடன் பரிமாறவும்.'],
    'benefits': ['Rich in fibre and calcium', 'No fermentation needed — a quick, healthy breakfast'],
    'benefitsLocal': ['நார்ச்சத்து, கால்சியம் நிறைந்தது', 'மாவு புளிக்க வைக்கத் தேவையில்லை — விரைவான ஆரோக்கிய உணவு'],
    'tip': 'Keep the flame medium so the dosa turns crisp, not dry.',
    'tipLocal': 'மிதமான தீயில் சுட்டால் தோசை மொறுமொறுப்பாக வரும்.',
  },
  {
    'id': 'ragi_kali',
    'name': 'Ragi kali',
    'nameLocal': 'ராகி களி',
    'minutes': 20,
    'serves': 2,
    'keys': ['ragi flour', 'ragi'],
    'ingredients': ['1 cup ragi flour', '2 cups water', '1/2 tsp salt', '1 tsp gingelly (sesame) oil'],
    'ingredientsLocal': ['1 கப் ராகி மாவு', '2 கப் தண்ணீர்', '1/2 தேக்கரண்டி உப்பு', '1 தேக்கரண்டி நல்லெண்ணெய்'],
    'steps': ['Boil the water with salt and a few drops of oil.', 'Lower the flame and add the ragi flour in one go — do not stir yet; cover for 2 minutes.', 'Now stir hard with a wooden ladle until smooth, with no dry flour left.', 'Cook covered on very low flame for 5 minutes, stirring once.', 'Wet your hands, shape into balls and serve with kuzhambu or keerai.'],
    'stepsLocal': ['உப்பு, சில துளி எண்ணெயுடன் தண்ணீரை கொதிக்க வைக்கவும்.', 'தீயைக் குறைத்து ராகி மாவை ஒரே முறையில் சேர்க்கவும் — உடனே கிளற வேண்டாம்; 2 நிமிடம் மூடி வைக்கவும்.', 'மரக்கரண்டியால் கட்டியில்லாமல் நன்கு கிளறவும்.', 'மிகக் குறைந்த தீயில் மூடி 5 நிமிடம் வேக விடவும்.', 'கையை நனைத்து உருண்டையாக்கி குழம்பு அல்லது கீரையுடன் பரிமாறவும்.'],
    'benefits': ['A traditional energy food for hard-working days', 'Rich in calcium for strong bones'],
    'benefitsLocal': ['உழைப்பு நாட்களுக்கான பாரம்பரிய சக்தி உணவு', 'எலும்புகளுக்கு கால்சியம் நிறைந்தது'],
    'tip': 'Best with keerai kadaiyal, kuzhambu or sambar.',
    'tipLocal': 'கீரை கடையல், குழம்பு அல்லது சாம்பாருடன் சுவையாக இருக்கும்.',
  },
  {
    'id': 'ragi_koozh',
    'name': 'Ragi koozh',
    'nameLocal': 'ராகி கூழ்',
    'minutes': 15,
    'serves': 3,
    'keys': ['ragi flour', 'ragi'],
    'ingredients': ['1/2 cup ragi flour', '3 cups water', '1 cup curd or buttermilk', '1 small onion, finely chopped', 'Salt to taste', 'Green chilli or raw mango (optional)'],
    'ingredientsLocal': ['1/2 கப் ராகி மாவு', '3 கப் தண்ணீர்', '1 கப் தயிர் அல்லது மோர்', '1 சிறிய வெங்காயம், பொடியாக நறுக்கியது', 'தேவைக்கு உப்பு', 'பச்சை மிளகாய் அல்லது மாங்காய் (விருப்பம்)'],
    'steps': ['Soak the ragi flour in 1 cup of water overnight to ferment lightly.', 'Boil 2 cups of water, add the soaked ragi and stir till thick and cooked (8–10 minutes).', 'Let it cool completely — it sets like a soft dough.', 'Mash it with curd or buttermilk and salt to a drinkable consistency.', 'Serve chilled with chopped onion and green chilli on the side.'],
    'stepsLocal': ['ராகி மாவை 1 கப் தண்ணீரில் இரவு முழுவதும் ஊற வைக்கவும்.', '2 கப் தண்ணீரை கொதிக்க வைத்து, ஊறிய ராகியைச் சேர்த்து கெட்டியாகும் வரை (8–10 நிமிடம்) கிளறவும்.', 'முழுவதும் ஆற விடவும் — மென்மையான களி போல் ஆகும்.', 'தயிர் அல்லது மோர், உப்பு சேர்த்து குடிக்கும் பதத்திற்கு கரைக்கவும்.', 'வெங்காயம், பச்சை மிளகாயுடன் குளிர்ச்சியாக பரிமாறவும்.'],
    'benefits': ['A cooling summer drink, traditional in Tamil Nadu', 'Lightly fermented — gentle on the stomach'],
    'benefitsLocal': ['கோடைக்கான குளிர்ச்சியான பாரம்பரிய பானம்', 'லேசாக புளித்தது — வயிற்றுக்கு இதமானது'],
    'tip': 'Make the base in the evening and mix with buttermilk in the morning.',
    'tipLocal': 'மாலையில் கூழ் தயாரித்து, காலையில் மோருடன் கரைக்கவும்.',
  },
  {
    'id': 'kambu_koozh',
    'name': 'Kambu koozh',
    'nameLocal': 'கம்பங்கூழ்',
    'minutes': 30,
    'serves': 3,
    'keys': ['kambu', 'pearl millet', 'bajra'],
    'ingredients': ['1 cup kambu (pearl millet)', '4 cups water', '1 cup buttermilk', 'Salt to taste', '1 small onion, chopped'],
    'ingredientsLocal': ['1 கப் கம்பு', '4 கப் தண்ணீர்', '1 கப் மோர்', 'தேவைக்கு உப்பு', '1 சிறிய வெங்காயம், நறுக்கியது'],
    'steps': ['Wash and soak kambu for 4 hours; drain and grind coarsely, like rava.', 'Boil 4 cups of water, add the ground kambu and cook on low flame, stirring, for 15–20 minutes.', 'Cool and keep covered overnight to ferment lightly.', 'Mix a portion with buttermilk and salt; serve with onion and chilli.'],
    'stepsLocal': ['கம்பைக் கழுவி 4 மணி நேரம் ஊற வைத்து, ரவை போல் கொரகொரப்பாக அரைக்கவும்.', '4 கப் தண்ணீரைக் கொதிக்க வைத்து, அரைத்த கம்பைச் சேர்த்து குறைந்த தீயில் 15–20 நிமிடம் கிளறி வேக வைக்கவும்.', 'ஆறியதும் மூடி இரவு முழுவதும் வைக்கவும்.', 'தேவையான அளவு எடுத்து மோர், உப்புடன் கரைத்து வெங்காயம், மிளகாயுடன் பரிமாறவும்.'],
    'benefits': ['Pearl millet is rich in iron and fibre', 'Keeps the body cool in summer'],
    'benefitsLocal': ['கம்பில் இரும்புச்சத்து, நார்ச்சத்து நிறைந்துள்ளது', 'கோடையில் உடலைக் குளிர்ச்சியாக வைக்கும்'],
    'tip': 'Store the cooked kambu in a clay pot for the best taste.',
    'tipLocal': 'வேக வைத்த கம்பை மண்பானையில் வைத்தால் சுவை அதிகம்.',
  },
  {
    'id': 'kambu_dosai',
    'name': 'Kambu dosai',
    'nameLocal': 'கம்பு தோசை',
    'minutes': 25,
    'serves': 4,
    'keys': ['kambu', 'pearl millet', 'bajra'],
    'ingredients': ['1 cup kambu', '1/2 cup idli rice', '1/4 cup urad dal', '1/2 tsp fenugreek', 'Salt to taste'],
    'ingredientsLocal': ['1 கப் கம்பு', '1/2 கப் இட்லி அரிசி', '1/4 கப் உளுந்து', '1/2 தேக்கரண்டி வெந்தயம்', 'தேவைக்கு உப்பு'],
    'steps': ['Soak kambu, rice, urad dal and fenugreek together for 5–6 hours.', 'Grind to a smooth batter, add salt and ferment for 8 hours.', 'Spread thin on a hot tawa, drizzle oil and cook till golden.', 'Serve with coconut chutney or sambar.'],
    'stepsLocal': ['கம்பு, அரிசி, உளுந்து, வெந்தயம் சேர்த்து 5–6 மணி நேரம் ஊற வைக்கவும்.', 'மென்மையாக அரைத்து உப்பு சேர்த்து 8 மணி நேரம் புளிக்க வைக்கவும்.', 'சூடான தோசைக்கல்லில் மெல்லியதாக ஊற்றி எண்ணெய் விட்டு பொன்னிறமாக சுடவும்.', 'தேங்காய் சட்னி அல்லது சாம்பாருடன் பரிமாறவும்.'],
    'benefits': ['More filling than a plain rice dosa', 'A good source of iron and fibre'],
    'benefitsLocal': ['சாதாரண தோசையை விட வயிறு நிறையும்', 'இரும்புச்சத்து, நார்ச்சத்து நிறைந்தது'],
    'tip': 'The same batter makes soft kambu idli too.',
    'tipLocal': 'இதே மாவில் மென்மையான கம்பு இட்லியும் செய்யலாம்.',
  },
  {
    'id': 'cholam_koozh',
    'name': 'Cholam koozh',
    'nameLocal': 'சோளக் கூழ்',
    'minutes': 30,
    'serves': 3,
    'keys': ['cholam', 'sorghum', 'jowar'],
    'ingredients': ['1 cup cholam (sorghum)', '4 cups water', '1 cup buttermilk', 'Salt to taste', 'Small onions, chopped'],
    'ingredientsLocal': ['1 கப் சோளம்', '4 கப் தண்ணீர்', '1 கப் மோர்', 'தேவைக்கு உப்பு', 'சின்ன வெங்காயம், நறுக்கியது'],
    'steps': ['Soak cholam for 6 hours and grind coarsely.', 'Cook in 4 cups of boiling water on low flame, stirring, for 20 minutes till thick.', 'Cool and rest overnight.', 'Mix with buttermilk and salt to a drinkable consistency; serve with small onions.'],
    'stepsLocal': ['சோளத்தை 6 மணி நேரம் ஊற வைத்து கொரகொரப்பாக அரைக்கவும்.', '4 கப் கொதிக்கும் தண்ணீரில் சேர்த்து குறைந்த தீயில் 20 நிமிடம் கெட்டியாகும் வரை கிளறவும்.', 'ஆறியதும் இரவு முழுவதும் வைக்கவும்.', 'மோர், உப்பு சேர்த்து கரைத்து சின்ன வெங்காயத்துடன் பரிமாறவும்.'],
    'benefits': ['A cooling, traditional village drink', 'Sorghum is naturally gluten-free and rich in fibre'],
    'benefitsLocal': ['குளிர்ச்சி தரும் பாரம்பரிய கிராமத்து பானம்', 'சோளம் இயற்கையாகவே பசையம் (gluten) இல்லாதது, நார்ச்சத்து நிறைந்தது'],
    'tip': 'Add a little crushed curry leaves or ginger for extra flavour.',
    'tipLocal': 'கறிவேப்பிலை அல்லது இஞ்சி சேர்த்தால் சுவை கூடும்.',
  },
  {
    'id': 'cholam_roti',
    'name': 'Cholam roti',
    'nameLocal': 'சோள ரொட்டி',
    'minutes': 25,
    'serves': 3,
    'keys': ['cholam', 'sorghum', 'jowar'],
    'ingredients': ['1 cup cholam (jowar) flour', '3/4 cup hot water', 'A pinch of salt', 'Extra flour for dusting'],
    'ingredientsLocal': ['1 கப் சோள மாவு', '3/4 கப் வெந்நீர்', 'சிறிது உப்பு', 'தூவ கூடுதல் மாவு'],
    'steps': ['Add salt to the flour and pour the hot water slowly, mixing with a spoon.', 'While still warm, knead into a soft, smooth dough.', 'Pat or roll each ball gently into a thin roti on a floured surface.', 'Cook on a hot tawa, sprinkling a little water on top; flip and press till it puffs.', 'Serve warm with curry or chutney.'],
    'stepsLocal': ['மாவில் உப்பு சேர்த்து வெந்நீரை மெதுவாக ஊற்றி கரண்டியால் கலக்கவும்.', 'சூடு இருக்கும்போதே மென்மையாகப் பிசையவும்.', 'உருண்டைகளாக்கி மாவு தூவி மெல்லிய ரொட்டியாகத் தட்டவும்.', 'சூடான தோசைக்கல்லில் போட்டு மேலே சிறிது தண்ணீர் தெளித்து, திருப்பி அழுத்தி உப்ப விடவும்.', 'குழம்பு அல்லது சட்னியுடன் சூடாக பரிமாறவும்.'],
    'benefits': ['A gluten-free alternative to wheat chapati', 'Rich in fibre — keeps you full'],
    'benefitsLocal': ['கோதுமை சப்பாத்திக்கு பசையம் இல்லாத மாற்று', 'நார்ச்சத்து நிறைந்தது — நீண்ட நேரம் பசி தாங்கும்'],
    'tip': 'Knead while the dough is still warm — it rolls without cracking.',
    'tipLocal': 'மாவு சூடாக இருக்கும்போதே பிசைந்தால் விரிசல் வராது.',
  },
  {
    'id': 'thinai_pongal',
    'name': 'Thinai pongal',
    'nameLocal': 'தினை பொங்கல்',
    'minutes': 30,
    'serves': 3,
    'keys': ['thinai', 'foxtail'],
    'ingredients': ['1/2 cup thinai (foxtail millet)', '1/4 cup moong dal', '3 cups water', '1 tsp pepper and 1 tsp cumin', 'Ginger, curry leaves and cashews', '2 tbsp ghee, salt'],
    'ingredientsLocal': ['1/2 கப் தினை', '1/4 கப் பாசிப்பருப்பு', '3 கப் தண்ணீர்', '1 தேக்கரண்டி மிளகு, 1 தேக்கரண்டி சீரகம்', 'இஞ்சி, கறிவேப்பிலை, முந்திரி', '2 மேசைக்கரண்டி நெய், உப்பு'],
    'steps': ['Dry-roast the moong dal lightly; wash with the thinai and soak for 20 minutes.', 'Pressure cook with 3 cups of water and salt for 4 whistles.', 'Heat ghee and fry pepper, cumin, ginger, curry leaves and cashews.', 'Pour over the cooked thinai, mash lightly and serve hot.'],
    'stepsLocal': ['பாசிப்பருப்பை லேசாக வறுத்து, தினையுடன் கழுவி 20 நிமிடம் ஊற வைக்கவும்.', '3 கப் தண்ணீர், உப்புடன் குக்கரில் 4 விசில் வேக வைக்கவும்.', 'நெய்யில் மிளகு, சீரகம், இஞ்சி, கறிவேப்பிலை, முந்திரி தாளிக்கவும்.', 'வெந்த தினையில் ஊற்றி லேசாக மசித்து சூடாக பரிமாறவும்.'],
    'benefits': ['A wholesome swap for rice pongal', 'Foxtail millet gives fibre and protein'],
    'benefitsLocal': ['அரிசி பொங்கலுக்கு சத்தான மாற்று', 'தினையில் நார்ச்சத்தும் புரதமும் உள்ளது'],
    'tip': 'Serve with coconut chutney and sambar for a festive breakfast.',
    'tipLocal': 'தேங்காய் சட்னி, சாம்பாருடன் பரிமாறினால் பண்டிகை காலை உணவு.',
  },
  {
    'id': 'samai_upma',
    'name': 'Samai upma',
    'nameLocal': 'சாமை உப்புமா',
    'minutes': 20,
    'serves': 2,
    'keys': ['samai', 'little millet'],
    'ingredients': ['1/2 cup samai (little millet)', '1 1/2 cups water', '1 onion and 1 green chilli, chopped', 'Mustard, urad dal and curry leaves', 'Grated carrot or beans (optional)', '1 tbsp oil, salt'],
    'ingredientsLocal': ['1/2 கப் சாமை', '1 1/2 கப் தண்ணீர்', '1 வெங்காயம், 1 பச்சை மிளகாய், நறுக்கியது', 'கடுகு, உளுந்து, கறிவேப்பிலை', 'துருவிய கேரட் அல்லது பீன்ஸ் (விருப்பம்)', '1 மேசைக்கரண்டி எண்ணெய், உப்பு'],
    'steps': ['Dry-roast the samai for 3 minutes until aromatic; keep aside.', 'Heat oil; add mustard, urad dal, curry leaves, onion and chilli and sauté.', 'Add the vegetables, water and salt and bring to a boil.', 'Add the samai, cover and cook on low flame for 10–12 minutes. Fluff and serve.'],
    'stepsLocal': ['சாமையை 3 நிமிடம் மணம் வரும் வரை வறுத்து வைக்கவும்.', 'எண்ணெயில் கடுகு, உளுந்து, கறிவேப்பிலை, வெங்காயம், மிளகாய் வதக்கவும்.', 'காய்கறி, தண்ணீர், உப்பு சேர்த்து கொதிக்க விடவும்.', 'சாமையைச் சேர்த்து மூடி, குறைந்த தீயில் 10–12 நிமிடம் வேக வைத்து கிளறி பரிமாறவும்.'],
    'benefits': ['Light and easy to digest', 'A fibre-rich alternative to rava upma'],
    'benefitsLocal': ['எளிதில் செரிக்கும் லேசான உணவு', 'ரவா உப்புமாவுக்கு நார்ச்சத்து நிறைந்த மாற்று'],
    'tip': 'Roasting the millet first keeps the grains separate.',
    'tipLocal': 'முதலில் வறுத்தால் சாமை ஒட்டாமல் உதிரியாக வரும்.',
  },
  {
    'id': 'varagu_sadam',
    'name': 'Varagu arisi sadam',
    'nameLocal': 'வரகு அரிசி சாதம்',
    'minutes': 25,
    'serves': 3,
    'keys': ['varagu', 'kodo'],
    'ingredients': ['1 cup varagu (kodo millet)', '2 1/2 cups water', 'A pinch of salt', 'A few drops of ghee or oil'],
    'ingredientsLocal': ['1 கப் வரகு', '2 1/2 கப் தண்ணீர்', 'சிறிது உப்பு', 'சில துளி நெய் அல்லது எண்ணெய்'],
    'steps': ['Wash the varagu 3–4 times and soak for 20 minutes.', 'Boil the water with salt and a few drops of ghee.', 'Add the drained varagu, cover and cook on low flame for 15 minutes (or 2 whistles).', 'Rest for 5 minutes, fluff and serve like rice with sambar, rasam or curd.'],
    'stepsLocal': ['வரகை 3–4 முறை கழுவி 20 நிமிடம் ஊற வைக்கவும்.', 'உப்பு, சில துளி நெய்யுடன் தண்ணீரைக் கொதிக்க வைக்கவும்.', 'வடித்த வரகைச் சேர்த்து மூடி, குறைந்த தீயில் 15 நிமிடம் (அல்லது 2 விசில்) வேக வைக்கவும்.', '5 நிமிடம் வைத்து, கிளறி சாதம் போல் சாம்பார், ரசம் அல்லது தயிருடன் பரிமாறவும்.'],
    'benefits': ['Use it in place of rice for everyday meals', 'Rich in fibre — helps you feel full'],
    'benefitsLocal': ['தினசரி சாதத்திற்குப் பதிலாகப் பயன்படுத்தலாம்', 'நார்ச்சத்து நிறைந்தது — வயிறு நிறைந்த உணர்வு'],
    'tip': 'If your family is new to millets, start with half varagu and half rice.',
    'tipLocal': 'முதலில் பாதி வரகு, பாதி அரிசி கலந்து பழகலாம்.',
  },
  {
    'id': 'kuthiraivali_kichadi',
    'name': 'Kuthiraivali kichadi',
    'nameLocal': 'குதிரைவாலி கிச்சடி',
    'minutes': 25,
    'serves': 3,
    'keys': ['kuthiraivali', 'barnyard'],
    'ingredients': ['1/2 cup kuthiraivali (barnyard millet)', '1/4 cup moong dal', '2 1/2 cups water', '1 onion, 1 tomato and mixed vegetables', 'Mustard, cumin and turmeric', '1 tbsp ghee, salt'],
    'ingredientsLocal': ['1/2 கப் குதிரைவாலி', '1/4 கப் பாசிப்பருப்பு', '2 1/2 கப் தண்ணீர்', '1 வெங்காயம், 1 தக்காளி, கலவை காய்கறி', 'கடுகு, சீரகம், மஞ்சள்', '1 மேசைக்கரண்டி நெய், உப்பு'],
    'steps': ['Wash the kuthiraivali and moong dal and soak for 15 minutes.', 'Heat ghee; temper mustard and cumin, then sauté onion, tomato and vegetables with turmeric.', 'Add the millet, dal, water and salt.', 'Pressure cook for 3 whistles and serve hot with pickle or raita.'],
    'stepsLocal': ['குதிரைவாலி, பாசிப்பருப்பைக் கழுவி 15 நிமிடம் ஊற வைக்கவும்.', 'நெய்யில் கடுகு, சீரகம் தாளித்து வெங்காயம், தக்காளி, காய்கறி, மஞ்சள் சேர்த்து வதக்கவும்.', 'குதிரைவாலி, பருப்பு, தண்ணீர், உப்பு சேர்க்கவும்.', 'குக்கரில் 3 விசில் வேக வைத்து ஊறுகாய் அல்லது ரைத்தாவுடன் பரிமாறவும்.'],
    'benefits': ['A complete one-pot meal with millet, dal and vegetables', 'Barnyard millet is light and easy to digest'],
    'benefitsLocal': ['சிறுதானியம், பருப்பு, காய்கறி சேர்ந்த முழுமையான ஒரு பாத்திர உணவு', 'குதிரைவாலி லேசானது, எளிதில் செரிக்கும்'],
    'tip': 'Add a spoon of ghee on top just before serving.',
    'tipLocal': 'பரிமாறும் முன் ஒரு கரண்டி நெய் சேர்க்கவும்.',
  },
  {
    'id': 'kollu_rasam',
    'name': 'Kollu rasam',
    'nameLocal': 'கொள்ளு ரசம்',
    'minutes': 30,
    'serves': 4,
    'keys': ['kollu', 'horse gram', 'horsegram'],
    'ingredients': ['1/4 cup kollu (horse gram)', '1 tomato', 'Lemon-sized ball of tamarind', '1 tsp pepper, 1 tsp cumin and 4 garlic cloves', 'Mustard, curry leaves and coriander', 'Salt, 1 tsp oil or ghee'],
    'ingredientsLocal': ['1/4 கப் கொள்ளு', '1 தக்காளி', 'எலுமிச்சை அளவு புளி', '1 தேக்கரண்டி மிளகு, 1 தேக்கரண்டி சீரகம், 4 பூண்டு பல்', 'கடுகு, கறிவேப்பிலை, கொத்தமல்லி', 'உப்பு, 1 தேக்கரண்டி எண்ணெய் அல்லது நெய்'],
    'steps': ['Soak the kollu overnight and pressure cook with 2 cups of water for 6–7 whistles.', 'Strain and keep the cooking water; coarsely crush the pepper, cumin and garlic.', 'Boil the tamarind water with tomato, salt and the crushed spices for 5 minutes.', 'Add the kollu water and a spoon of mashed kollu; take off the heat when it froths — do not boil hard.', 'Temper mustard and curry leaves, add coriander and serve with rice or as a soup.'],
    'stepsLocal': ['கொள்ளை இரவு ஊற வைத்து 2 கப் தண்ணீருடன் குக்கரில் 6–7 விசில் வேக வைக்கவும்.', 'வடித்த தண்ணீரை எடுத்து வைக்கவும்; மிளகு, சீரகம், பூண்டை ஒன்றிரண்டாக இடிக்கவும்.', 'புளித்தண்ணீரில் தக்காளி, உப்பு, இடித்த மசாலா சேர்த்து 5 நிமிடம் கொதிக்க விடவும்.', 'கொள்ளு தண்ணீர், சிறிது மசித்த கொள்ளு சேர்த்து நுரைத்து வரும்போது இறக்கவும்.', 'கடுகு, கறிவேப்பிலை தாளித்து கொத்தமல்லி சேர்த்து சாதம் அல்லது சூப்பாக பரிமாறவும்.'],
    'benefits': ['A warming rasam, traditional for cold and rainy days', 'Horse gram is rich in protein and iron'],
    'benefitsLocal': ['குளிர், மழைக்கால பாரம்பரிய சூடான ரசம்', 'கொள்ளில் புரதம், இரும்புச்சத்து நிறைந்துள்ளது'],
    'tip': 'Use the cooked kollu for sundal or thuvaiyal — nothing is wasted.',
    'tipLocal': 'வெந்த கொள்ளை சுண்டல் அல்லது துவையலுக்குப் பயன்படுத்தலாம்.',
  },
  {
    'id': 'payaru_sundal',
    'name': 'Pachai payaru sundal',
    'nameLocal': 'பச்சைப் பயறு சுண்டல்',
    'minutes': 20,
    'serves': 3,
    'keys': ['pachai payaru', 'green gram', 'greengram', 'payaru', 'moong'],
    'ingredients': ['1 cup pachai payaru (green gram)', '2 tbsp grated coconut', '1 dry red chilli', 'Mustard, urad dal and curry leaves', 'A pinch of asafoetida', '1 tsp oil, salt'],
    'ingredientsLocal': ['1 கப் பச்சைப் பயறு', '2 மேசைக்கரண்டி தேங்காய் துருவல்', '1 காய்ந்த மிளகாய்', 'கடுகு, உளுந்து, கறிவேப்பிலை', 'சிறிது பெருங்காயம்', '1 தேக்கரண்டி எண்ணெய், உப்பு'],
    'steps': ['Soak the green gram for 6 hours (or overnight).', 'Pressure cook with salt for 2 whistles — cooked but not mushy — and drain.', 'Temper mustard, urad dal, red chilli, curry leaves and asafoetida in oil.', 'Add the green gram and coconut, toss well and serve warm.'],
    'stepsLocal': ['பச்சைப் பயறை 6 மணி நேரம் (அல்லது இரவு) ஊற வைக்கவும்.', 'உப்புடன் குக்கரில் 2 விசில் — குழையாமல் வேக வைத்து வடிக்கவும்.', 'எண்ணெயில் கடுகு, உளுந்து, மிளகாய், கறிவேப்பிலை, பெருங்காயம் தாளிக்கவும்.', 'பயறு, தேங்காய் சேர்த்து கிளறி சூடாக பரிமாறவும்.'],
    'benefits': ['A protein-rich evening snack', 'Light, easy to digest and good for children'],
    'benefitsLocal': ['புரதம் நிறைந்த மாலை சிற்றுண்டி', 'லேசானது, குழந்தைகளுக்கு ஏற்றது'],
    'tip': 'Sprout the green gram for a day for even more nutrition.',
    'tipLocal': 'ஒரு நாள் முளைகட்டினால் சத்து இன்னும் கூடும்.',
  },
  {
    'id': 'mochai_kuzhambu',
    'name': 'Mochai kuzhambu',
    'nameLocal': 'மொச்சைக் குழம்பு',
    'minutes': 40,
    'serves': 4,
    'keys': ['mochai', 'field bean', 'bean'],
    'ingredients': ['1/2 cup mochai (field beans)', 'Lemon-sized ball of tamarind', '10 small onions and 1 tomato', '2 tbsp sambar powder', 'Mustard, fenugreek and curry leaves', '2 tbsp gingelly oil, salt'],
    'ingredientsLocal': ['1/2 கப் மொச்சை', 'எலுமிச்சை அளவு புளி', '10 சின்ன வெங்காயம், 1 தக்காளி', '2 மேசைக்கரண்டி சாம்பார் பொடி', 'கடுகு, வெந்தயம், கறிவேப்பிலை', '2 மேசைக்கரண்டி நல்லெண்ணெய், உப்பு'],
    'steps': ['Soak the mochai overnight and pressure cook for 4–5 whistles until soft.', 'Heat gingelly oil; temper mustard, fenugreek and curry leaves, then sauté small onions and tomato.', 'Add sambar powder, tamarind water and salt; boil for 8 minutes.', 'Add the cooked mochai and simmer for 10 minutes until the gravy thickens. Serve with rice.'],
    'stepsLocal': ['மொச்சையை இரவு ஊற வைத்து குக்கரில் 4–5 விசில் மென்மையாக வேக வைக்கவும்.', 'நல்லெண்ணெயில் கடுகு, வெந்தயம், கறிவேப்பிலை தாளித்து சின்ன வெங்காயம், தக்காளி வதக்கவும்.', 'சாம்பார் பொடி, புளித்தண்ணீர், உப்பு சேர்த்து 8 நிமிடம் கொதிக்க விடவும்.', 'வெந்த மொச்சையைச் சேர்த்து 10 நிமிடம் கெட்டியாகும் வரை கொதிக்க விட்டு சாதத்துடன் பரிமாறவும்.'],
    'benefits': ['A hearty, protein-rich village-style kuzhambu', 'Field beans add fibre and keep you full'],
    'benefitsLocal': ['புரதம் நிறைந்த கிராமத்து சுவைக் குழம்பு', 'மொச்சை நார்ச்சத்து தந்து பசி தாங்கும்'],
    'tip': 'Like most kuzhambu, it tastes even better the next day.',
    'tipLocal': 'மற்ற குழம்புகளைப் போல மறுநாள் இன்னும் சுவையாக இருக்கும்.',
  },
];
