import 'locale_controller.dart';

/// Looks up a translated string for the app's current language.
/// Usage: AppStrings.t('save') — falls back to English, then to the raw
/// key itself, if a translation is ever missing, so the app never shows
/// a blank label.
///
/// Honest scope note: covers navigation, login, Dashboard, and every
/// remaining screen's static UI text (labels, buttons, headers, hints,
/// empty states). Highly dynamic strings — Firestore error text
/// interpolated into messages like "Could not save sale: $e" — keep
/// their static Tamil prefix but the interpolated part stays whatever
/// the underlying system reports (in English), since that text comes
/// from the SDK itself, not from this app.
class AppStrings {
  static String t(String key) {
    final lang = LocaleController.instance.language;
    return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Navigation
      'nav_home': 'Home',
      'nav_sales': 'Sales',
      'nav_inventory': 'Inventory',
      'nav_credit': 'Credit',
      'nav_suppliers': 'Suppliers',

      // Login
      'app_name': 'Madhura Agro Traders',
      'store_management': 'Store management',
      'sign_in': 'Sign In',
      'signing_in': 'Signing in…',
      'email': 'Email',
      'password': 'Password',

      // Dashboard
      'store_overview': 'Store overview',
      'todays_sales': "Today's Sales",
      'todays_collections': "Today's Collections",
      'total_outstanding_credit': 'Total Outstanding Credit',
      'todays_gross_profit': "Today's Gross Profit",
      'supplier_dues': 'Supplier Dues',
      'low_stock_alerts': 'Low Stock Alerts',
      'outstanding_vendors': 'Outstanding Vendors (60+ days)',
      'sales_trend': 'Sales Trend',
      'sign_out': 'Sign out',
      'sign_out_confirm': 'Sign out?',

      // Common actions (reused everywhere)
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'retry': 'Retry',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',

      // Language picker
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'tamil': 'Tamil',

      // Sales screen
      'sales_title': 'Sales',
      'new_sale': 'New Sale',
      're_enter_sale': 'Re-enter Sale',
      'add_vendor_credit_customer': 'Add Vendor (Credit Customer)',
      'add_at_least_one_item': 'Add at least one item',
      'cancelled': 'CANCELLED',
      'cancel_sale': 'Cancel Sale',
      'cancel_sale_confirm': 'Cancel this sale?',
      'cart': 'Cart',
      'cash': 'Cash',
      'complete_sale': 'Complete Sale',
      'continue_label': 'Continue',
      'could_not_cancel_sale': 'Could not cancel sale',
      'could_not_load_sales': 'Could not load sales',
      'could_not_modify_sale': 'Could not modify sale',
      'could_not_save_sale': 'Could not save sale',
      'delete_cancel_sale': 'Delete (Cancel Sale)',
      'discount': 'Discount',
      'full_credit': 'Full Credit',
      'partial_credit': 'Partial Credit',
      'last_30_days': 'Last 30 days',
      'modify': 'Modify',
      'modify_sale_confirm': 'Modify this sale?',
      'monthly_sales_trend': 'Monthly Sales Trend',
      'no_sales_recorded_yet': 'No sales recorded yet.',
      'no_sales_tap_add': 'No sales recorded. Tap + to add a sale.',
      'no_keep_it': 'No, keep it',
      'partial': 'Partial',
      'payment_due_by': 'Payment due by (optional)',
      'quantity': 'Quantity',
      'sale_hash': 'Sale #',
      'search_product_add': 'Search a product above and tap it to add',
      'select_vendor_credit': 'Select a vendor for credit sales',
      'set_label': 'Set',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'amount_collected_now': 'Amount collected now',
      'name': 'Name',
      'phone': 'Phone',
      'place': 'Place',
      'type_product_search': 'Type a product name to search',

      // Inventory screen
      'inventory_title': 'Inventory',
      'delete_product': 'Delete Product',
      'low_stock': 'Low stock',
      'new_supplier': 'New Supplier',
      'no_movements_yet': 'No movements recorded yet.',
      'no_products_tap_add': 'No products yet. Tap + to add one.',
      'could_not_load_inventory': 'Could not load inventory',
      'save_product': 'Save Product',
      'category': 'Category',
      'cost_price': 'Cost price',
      'current_quantity': 'Current quantity',
      'product_name': 'Product name',
      'reorder_level': 'Reorder level (low stock alert)',
      'search_products': 'Search products',
      'selling_price': 'Selling price',
      'sub_category': 'Sub-category',
      'supplier_optional': 'Supplier (optional)',
      'unit': 'Unit',

      // Vendors screen
      'add_credit': 'Add Credit',
      'add_vendor': 'Add Vendor',
      'collect_payment': 'Collect Payment',
      'could_not_delete': 'Could not delete',
      'could_not_load_history': 'Could not load history',
      'could_not_record_payment': 'Could not record payment',
      'could_not_save': 'Could not save',
      'credit_given_on': 'Credit given on',
      'current_balance': 'Current Balance',
      'date': 'Date',
      'edit_vendor': 'Edit Vendor',
      'ledger': 'Ledger',
      'no_item_details': 'No item details recorded for this sale.',
      'no_transactions_yet': 'No transactions yet.',
      'outstanding': 'Outstanding',
      'payment': 'Payment',
      'transaction_history': 'Transaction History',
      'vendor_credit': 'Vendor Credit',
      'amount': 'Amount',
      'notes_optional': 'Notes (optional)',
      'opening_balance_owed': 'Opening balance owed',
      'credit_given': 'Credit given',
      'payment_received': 'Payment received',
      'balance_abbr': 'Bal',

      // Suppliers screen
      'add_supplier': 'Add Supplier',
      'edit_supplier': 'Edit Supplier',
      'add_at_least_one_product': 'Add at least one product',
      'amount_owed_supplier': 'Amount Owed to Supplier',
      'could_not_load_suppliers': 'Could not load suppliers',
      'new_purchase': 'New Purchase',
      'no_product_details_purchase': 'No product details recorded for this purchase.',
      'no_products_added_yet': 'No products added yet.',
      'no_suppliers_tap_add': 'No suppliers yet. Tap + to add one.',
      'pay_supplier': 'Pay Supplier',
      'purchase_items': 'Purchase items',
      'record_payment_made': 'Record Payment Made',
      'save_purchase': 'Save Purchase',
      'suppliers_title': 'Suppliers',
      'tap_product_add_qty': 'Tap a product to add it, then set quantity and cost per unit.',
      'total_owed_suppliers': 'Total Owed to Suppliers',
      'address': 'Address',
      'cost_per_unit': 'Cost/unit',
      'notes_invoice': 'Notes (invoice no. etc.)',
      'opening_balance_owed_them': 'Opening balance owed to them',
      'purchase': 'Purchase',
      'payment_made': 'Payment made',
      'tap_view_products': 'tap to view products',
      'qty': 'Qty',

      // Reports & Vendor Insights
      'reports_trends': 'Reports & Trends',
      'no_sales_in_period': 'No sales in this period.',
      'revenue': 'Revenue',
      'cost': 'Cost',
      'gross_profit': 'Gross Profit',
      'sales_count': 'Sales Count',
      'week': 'Week',
      'month': 'Month',
      'custom': 'Custom',
      'revenue_over_period': 'Revenue over period',
      'payment_mix': 'Payment Mix',
      'top_products': 'Top Products',
      'by_category': 'By Category',
      'by_subcategory': 'By Subcategory',
      'vendor_insights': 'Vendor Insights',
      'location': 'Location',
      'frequency': 'Frequency',
      'long_pending': 'Long Pending',
      'no_vendors_yet': 'No vendors yet.',
      'no_location_set': 'No location set',
      'nobody_pending': 'Nobody has an outstanding balance right now — nothing pending.',
      'no_purchases_yet': 'No purchases yet',
      'last_purchase': 'last',
      'outstanding_days': 'Outstanding',
      'days': 'days',
      'bucket_90_plus': '90+ days',
      'bucket_61_90': '61–90 days',
      'bucket_31_60': '31–60 days',
      'bucket_0_30': '0–30 days',

      // Data Sync screen
      'data_export_import': 'Data Export & Import',
      'export': 'Export',
      'export_all_data': 'Export All Data (CSV)',
      'import': 'Import',
      'import_products_csv': 'Import Products CSV',
      'import_supplier_txn_history': 'Import Supplier Transaction History CSV',
      'import_suppliers_csv': 'Import Suppliers CSV',
      'import_vendor_credit_history': 'Import Vendor Credit History CSV',
      'import_vendors_csv': 'Import Vendors CSV',
      'sync_explanation': 'This is for sharing data between two phones — it is not live syncing. Each phone keeps its own copy of the data; export here and send the files to the other phone, then import there to bring the changes in.',
      'export_explanation': 'Creates a CSV file for every part of the app (products, vendors, suppliers, sales, credit and supplier ledgers, stock history) and opens the share menu so you can send them via WhatsApp, email, Google Drive, etc.',
      'import_explanation': 'Products, vendors, and suppliers update or add records by name. Vendor/supplier credit history can also be imported — each row (date, name, type, amount, notes) is replayed the same safe way as entering it by hand, so balances stay correct. Sales themselves are still export-only, since importing one back would double-count stock.',
      'vendor_credit_csv_columns': 'Columns: date, vendor_name, type (CREDIT or PAYMENT), amount, notes — same shape as the exported credit_transactions.csv.',
      'supplier_txn_csv_columns': 'Columns: date, supplier_name, type (PURCHASE or PAYMENT), amount, notes.',

      // Today's Collections
      'no_collections_today': 'No collections recorded yet today.',
      'could_not_load_collections': 'Could not load collections',
      'total_collected_today': 'Total collected today',
      'payments': 'payments',
    },
    'ta': {
      // Navigation
      'nav_home': 'முகப்பு',
      'nav_sales': 'விற்பனை',
      'nav_inventory': 'சரக்கு',
      'nav_credit': 'கடன்',
      'nav_suppliers': 'சப்ளையர்கள்',

      // Login
      'app_name': 'மதுரா அக்ரோ டிரேடர்ஸ்',
      'store_management': 'கடை மேலாண்மை',
      'sign_in': 'உள்நுழை',
      'signing_in': 'உள்நுழைகிறது…',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',

      // Dashboard
      'store_overview': 'கடையின் சுருக்கம்',
      'todays_sales': 'இன்றைய விற்பனை',
      'todays_collections': 'இன்றைய வசூல்',
      'total_outstanding_credit': 'மொத்த நிலுவை கடன்',
      'todays_gross_profit': 'இன்றைய மொத்த லாபம்',
      'supplier_dues': 'சப்ளையர் நிலுவைத் தொகை',
      'low_stock_alerts': 'குறைந்த இருப்பு எச்சரிக்கை',
      'outstanding_vendors': 'நிலுவை வாடிக்கையாளர்கள் (60+ நாட்கள்)',
      'sales_trend': 'விற்பனை போக்கு',
      'sign_out': 'வெளியேறு',
      'sign_out_confirm': 'வெளியேற வேண்டுமா?',

      // Common actions (reused everywhere)
      'save': 'சேமி',
      'cancel': 'ரத்துசெய்',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'add': 'சேர்',
      'search': 'தேடு',
      'retry': 'மீண்டும் முயற்சி',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'close': 'மூடு',

      // Language picker
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'english': 'English',
      'tamil': 'தமிழ்',

      // Sales screen
      'sales_title': 'விற்பனை',
      'new_sale': 'புதிய விற்பனை',
      're_enter_sale': 'விற்பனையை மீண்டும் உள்ளிடவும்',
      'add_vendor_credit_customer': 'வாடிக்கையாளரைச் சேர் (கடன் வாடிக்கையாளர்)',
      'add_at_least_one_item': 'குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'cancel_sale': 'விற்பனையை ரத்து செய்',
      'cancel_sale_confirm': 'இந்த விற்பனையை ரத்து செய்யவா?',
      'cart': 'கார்ட்',
      'cash': 'பணம்',
      'complete_sale': 'விற்பனையை முடி',
      'continue_label': 'தொடரவும்',
      'could_not_cancel_sale': 'விற்பனையை ரத்து செய்ய முடியவில்லை',
      'could_not_load_sales': 'விற்பனைகளை ஏற்ற முடியவில்லை',
      'could_not_modify_sale': 'விற்பனையை திருத்த முடியவில்லை',
      'could_not_save_sale': 'விற்பனையை சேமிக்க முடியவில்லை',
      'delete_cancel_sale': 'நீக்கு (விற்பனையை ரத்து செய்)',
      'discount': 'தள்ளுபடி',
      'full_credit': 'முழு கடன்',
      'partial_credit': 'பகுதி கடன்',
      'last_30_days': 'கடந்த 30 நாட்கள்',
      'modify': 'திருத்து',
      'modify_sale_confirm': 'இந்த விற்பனையை திருத்தவா?',
      'monthly_sales_trend': 'மாதாந்திர விற்பனை போக்கு',
      'no_sales_recorded_yet': 'இன்னும் விற்பனை பதிவு செய்யப்படவில்லை.',
      'no_sales_tap_add': 'விற்பனை பதிவு இல்லை. விற்பனை சேர்க்க + ஐ தட்டவும்.',
      'no_keep_it': 'வேண்டாம், வைத்திரு',
      'partial': 'பகுதி',
      'payment_due_by': 'செலுத்த வேண்டிய தேதி (விரும்பினால்)',
      'quantity': 'அளவு',
      'sale_hash': 'விற்பனை எண்',
      'search_product_add': 'மேலே ஒரு பொருளைத் தேடி, சேர்க்க தட்டவும்',
      'select_vendor_credit': 'கடன் விற்பனைக்கு ஒரு வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
      'set_label': 'அமை',
      'subtotal': 'கூட்டுத்தொகை',
      'total': 'மொத்தம்',
      'amount_collected_now': 'இப்போது வசூலித்த தொகை',
      'name': 'பெயர்',
      'phone': 'தொலைபேசி',
      'place': 'இடம்',
      'type_product_search': 'தேட பொருளின் பெயரை தட்டச்சு செய்யவும்',

      // Inventory screen
      'inventory_title': 'சரக்கு',
      'delete_product': 'பொருளை நீக்கு',
      'low_stock': 'குறைந்த இருப்பு',
      'new_supplier': 'புதிய சப்ளையர்',
      'no_movements_yet': 'இன்னும் இருப்பு மாற்றங்கள் பதிவு செய்யப்படவில்லை.',
      'no_products_tap_add': 'பொருட்கள் இல்லை. ஒன்றைச் சேர்க்க + ஐ தட்டவும்.',
      'could_not_load_inventory': 'சரக்கு பட்டியலை ஏற்ற முடியவில்லை',
      'save_product': 'பொருளை சேமி',
      'category': 'வகை',
      'cost_price': 'வாங்கும் விலை',
      'current_quantity': 'தற்போதைய அளவு',
      'product_name': 'பொருளின் பெயர்',
      'reorder_level': 'மறு ஆர்டர் அளவு (குறைந்த இருப்பு எச்சரிக்கை)',
      'search_products': 'பொருட்களைத் தேடு',
      'selling_price': 'விற்பனை விலை',
      'sub_category': 'துணை வகை',
      'supplier_optional': 'சப்ளையர் (விரும்பினால்)',
      'unit': 'அலகு',

      // Vendors screen
      'add_credit': 'கடன் சேர்',
      'add_vendor': 'வாடிக்கையாளரைச் சேர்',
      'collect_payment': 'பணம் வசூலி',
      'could_not_delete': 'நீக்க முடியவில்லை',
      'could_not_load_history': 'வரலாற்றை ஏற்ற முடியவில்லை',
      'could_not_record_payment': 'பணம் செலுத்தியதை பதிவு செய்ய முடியவில்லை',
      'could_not_save': 'சேமிக்க முடியவில்லை',
      'credit_given_on': 'கடன் கொடுத்த தேதி',
      'current_balance': 'தற்போதைய இருப்பு',
      'date': 'தேதி',
      'edit_vendor': 'வாடிக்கையாளரைத் திருத்து',
      'ledger': 'கணக்கு பதிவேடு',
      'no_item_details': 'இந்த விற்பனைக்கு பொருள் விவரங்கள் பதிவு செய்யப்படவில்லை.',
      'no_transactions_yet': 'இன்னும் பரிவர்த்தனைகள் இல்லை.',
      'outstanding': 'நிலுவை',
      'payment': 'பணம் செலுத்துதல்',
      'transaction_history': 'பரிவர்த்தனை வரலாறு',
      'vendor_credit': 'வாடிக்கையாளர் கடன்',
      'amount': 'தொகை',
      'notes_optional': 'குறிப்புகள் (விரும்பினால்)',
      'opening_balance_owed': 'தொடக்க நிலுவைத் தொகை',
      'credit_given': 'கொடுத்த கடன்',
      'payment_received': 'பெற்ற பணம்',
      'balance_abbr': 'இருப்பு',

      // Suppliers screen
      'add_supplier': 'சப்ளையரைச் சேர்',
      'edit_supplier': 'சப்ளையரைத் திருத்து',
      'add_at_least_one_product': 'குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
      'amount_owed_supplier': 'சப்ளையருக்கு செலுத்த வேண்டிய தொகை',
      'could_not_load_suppliers': 'சப்ளையர்களை ஏற்ற முடியவில்லை',
      'new_purchase': 'புதிய கொள்முதல்',
      'no_product_details_purchase': 'இந்த கொள்முதலுக்கு பொருள் விவரங்கள் பதிவு செய்யப்படவில்லை.',
      'no_products_added_yet': 'இன்னும் பொருட்கள் சேர்க்கப்படவில்லை.',
      'no_suppliers_tap_add': 'சப்ளையர்கள் இல்லை. ஒன்றைச் சேர்க்க + ஐ தட்டவும்.',
      'pay_supplier': 'சப்ளையருக்கு பணம் செலுத்து',
      'purchase_items': 'கொள்முதல் பொருட்கள்',
      'record_payment_made': 'செலுத்திய பணத்தை பதிவு செய்',
      'save_purchase': 'கொள்முதலை சேமி',
      'suppliers_title': 'சப்ளையர்கள்',
      'tap_product_add_qty': 'ஒரு பொருளைத் தட்டி சேர்க்கவும், பின் அளவு மற்றும் ஒரு அலகுக்கான விலையை அமைக்கவும்.',
      'total_owed_suppliers': 'சப்ளையர்களுக்கு செலுத்த வேண்டிய மொத்தத் தொகை',
      'address': 'முகவரி',
      'cost_per_unit': 'ஒரு அலகுக்கான விலை',
      'notes_invoice': 'குறிப்புகள் (பில் எண் போன்றவை)',
      'opening_balance_owed_them': 'அவர்களுக்கு செலுத்த வேண்டிய தொடக்க நிலுவை',
      'purchase': 'கொள்முதல்',
      'payment_made': 'செலுத்திய தொகை',
      'tap_view_products': 'பொருட்களைப் பார்க்க தட்டவும்',
      'qty': 'எண்ணிக்கை',

      // Reports & Vendor Insights
      'reports_trends': 'அறிக்கைகள் & போக்குகள்',
      'no_sales_in_period': 'இந்த காலகட்டத்தில் விற்பனை இல்லை.',
      'revenue': 'வருவாய்',
      'cost': 'செலவு',
      'gross_profit': 'மொத்த லாபம்',
      'sales_count': 'விற்பனை எண்ணிக்கை',
      'week': 'வாரம்',
      'month': 'மாதம்',
      'custom': 'விருப்பம்',
      'revenue_over_period': 'காலப்போக்கில் வருவாய்',
      'payment_mix': 'பணம் செலுத்தும் விதம்',
      'top_products': 'சிறந்த பொருட்கள்',
      'by_category': 'வகை வாரியாக',
      'by_subcategory': 'துணை வகை வாரியாக',
      'vendor_insights': 'வாடிக்கையாளர் பகுப்பாய்வு',
      'location': 'இடம்',
      'frequency': 'அடிக்கடி வாங்குதல்',
      'long_pending': 'நீண்ட நாள் நிலுவை',
      'no_vendors_yet': 'வாடிக்கையாளர்கள் இல்லை.',
      'no_location_set': 'இடம் குறிப்பிடப்படவில்லை',
      'nobody_pending': 'யாருக்கும் தற்போது நிலுவைத் தொகை இல்லை — எதுவும் நிலுவையில் இல்லை.',
      'no_purchases_yet': 'இன்னும் வாங்கவில்லை',
      'last_purchase': 'கடைசி',
      'outstanding_days': 'நிலுவை',
      'days': 'நாட்கள்',
      'bucket_90_plus': '90+ நாட்கள்',
      'bucket_61_90': '61–90 நாட்கள்',
      'bucket_31_60': '31–60 நாட்கள்',
      'bucket_0_30': '0–30 நாட்கள்',

      // Data Sync screen
      'data_export_import': 'தரவு ஏற்றுமதி & இறக்குமதி',
      'export': 'ஏற்றுமதி',
      'export_all_data': 'அனைத்து தரவையும் ஏற்றுமதி செய் (CSV)',
      'import': 'இறக்குமதி',
      'import_products_csv': 'பொருட்கள் CSV இறக்குமதி',
      'import_supplier_txn_history': 'சப்ளையர் பரிவர்த்தனை வரலாறு CSV இறக்குமதி',
      'import_suppliers_csv': 'சப்ளையர்கள் CSV இறக்குமதி',
      'import_vendor_credit_history': 'வாடிக்கையாளர் கடன் வரலாறு CSV இறக்குமதி',
      'import_vendors_csv': 'வாடிக்கையாளர்கள் CSV இறக்குமதி',
      'sync_explanation': 'இது இரண்டு போன்களுக்கு இடையே தரவைப் பகிர்வதற்கானது — இது நேரடி ஒத்திசைவு அல்ல. ஒவ்வொரு போனும் அதன் சொந்த தரவை வைத்திருக்கும்; இங்கே ஏற்றுமதி செய்து, கோப்புகளை மற்ற போனுக்கு அனுப்பவும், பின் அங்கே இறக்குமதி செய்து மாற்றங்களைச் சேர்க்கவும்.',
      'export_explanation': 'ஆப்பின் ஒவ்வொரு பகுதிக்கும் (பொருட்கள், வாடிக்கையாளர்கள், சப்ளையர்கள், விற்பனை, கடன் மற்றும் சப்ளையர் கணக்குகள், இருப்பு வரலாறு) ஒரு CSV கோப்பை உருவாக்கி, WhatsApp, மின்னஞ்சல், Google Drive போன்றவற்றின் மூலம் அனுப்ப பகிர்வு மெனுவைத் திறக்கும்.',
      'import_explanation': 'பொருட்கள், வாடிக்கையாளர்கள், சப்ளையர்கள் ஆகியவை பெயரின் மூலம் புதுப்பிக்கப்படும் அல்லது சேர்க்கப்படும். வாடிக்கையாளர்/சப்ளையர் கடன் வரலாற்றையும் இறக்குமதி செய்யலாம் — ஒவ்வொரு வரிசையும் (date, name, type, amount, notes) கைமுறையாக உள்ளிடுவது போலவே பாதுகாப்பாக செயல்படுத்தப்படும், இதனால் நிலுவைத் தொகைகள் சரியாக இருக்கும். விற்பனை பதிவுகள் இறக்குமதிக்கு கிடைக்காது, ஏனெனில் மீண்டும் இறக்குமதி செய்தால் இருப்பு இரட்டிப்பாகிவிடும்.',
      'vendor_credit_csv_columns': 'நெடுவரிசைகள்: date, vendor_name, type (CREDIT அல்லது PAYMENT), amount, notes — ஏற்றுமதி செய்யப்பட்ட credit_transactions.csv-ஐப் போலவே.',
      'supplier_txn_csv_columns': 'நெடுவரிசைகள்: date, supplier_name, type (PURCHASE அல்லது PAYMENT), amount, notes.',

      // Today's Collections
      'no_collections_today': 'இன்று இன்னும் வசூல் பதிவு செய்யப்படவில்லை.',
      'could_not_load_collections': 'வசூல் விவரங்களை ஏற்ற முடியவில்லை',
      'total_collected_today': 'இன்று வசூலித்த மொத்தத் தொகை',
      'payments': 'பணம் செலுத்துதல்கள்',
    },
  };
}
